# Philips hue https://github.com/robmarkcole/Hue-sensors-HASS
# - platform: huesensor

- platform: fronius_inverter
  ip_address: 192.168.86.34
  device_id: 1
  powerflow: true
  monitored_conditions:
    - ac_power
    - ac_current
    - ac_voltage
    - ac_frequency
    - dc_current
    - dc_voltage
    - day_energy
    - year_energy
    - total_energy
    - grid_usage
    - house_load
    - panel_status
    # powerflow
    # - grid_usage
    # - house_load
    # - panel_status

#- platform: fronius
#  resource: http://192.168.86.34
#  monitored_conditions:
#    - sensor_type: inverter
#      device: 1
#    - sensor_type: meter
#      scope: system
#    - sensor_type: power_flow

#https://home-assistant.io/components/sensor.systemmonitor/
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: last_boot
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0enp0s25
    - type: network_out
      arg: enp0s25


# Weather prediction
- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

# Dark Sky
#- platform: darksky
#  api_key: !secret darksky_token
#  forecast:
#    - 0
#  monitored_conditions:
#    - summary
#    - icon
#    - temperature

# Google wifi
- platform: google_wifi
  host: 192.168.86.1
  name: Internet

# Verisure mail sensor
- platform: imap_email_content
  server: imap.gmail.com
  port: 993
  name: Verisure Mail
  username: !secret imap_email_username
  password: !secret imap_email_password
  senders:
    - no-reply@verisure.com

- platform: template
  sensors:
    unlocked_by:
      friendly_name: "Unlocked by"
      entity_id: "sensor.verisure_mail"
      value_template: >-
        {% if states.sensor.verisure_mail.attributes.subject == "Upplåst utifrån" %}
          {% if states.sensor.verisure_mail.attributes.body.find("Niklas") | int >= 0 %}
            Niklas
          {% elif states.sensor.verisure_mail.attributes.body.find("Ming") | int >= 0 %}
            Ming
          {% elif states.sensor.verisure_mail.attributes.body.find("Noah") | int >= 0 %}
            Noah
          {% elif states.sensor.verisure_mail.attributes.body.find("Alex") | int >= 0 %}
            Alex
          {% elif states.sensor.verisure_mail.attributes.body.find("Nadja") | int >= 0 %}
            Nadja
          {% elif states.sensor.verisure_mail.attributes.body.find("Nicholas") | int >= 0 %}
            Nicholas
          {% else %}
            Unknown
          {% endif %}
        {% endif %}
    # low_battery:
    #   friendly_name: "Low Battery"
    #   entity_id: sensor.time
    #   value_template: >
    #     {%- set threshold = 80 -%}
    #     {%- set domains = ['light', 'binary_sensor', 'switch', 'sensor', 'zwave', 'lock'] -%}
    #     {%- for domain in domains -%}
    #     {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
    #     {%- if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) -%}
    #       {{ item.entity_id }} ({{ item.attributes['battery_level'] }}){%- if not loop.last %}, {% endif -%}{% endif -%}
    #       {%- if "battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown") -%}
    #       {{ item.entity_id }} ({{ item.state }}){%- if not loop.last %}, {% endif -%} {% endif -%}
    #     {%- endfor -%}
    #     {%- endfor -%}
- platform: rest
  # hourly https://www.smhi.se/wpt-a/backend_observation/metobs/station/number/97100
  resource: https://opendata-download-metobs.smhi.se/api/version/latest/parameter/5/station/98040/period/latest-day/data.json
  name: Tullinge regn
  json_attributes:
    - value
  value_template: '{{ value_json.value[0] }}'
- platform: template
  sensors:
    precipitation_cumulative_last_day:
      friendly_name: 'Last days rain'
      value_template: '{{ states.sensor.tullinge_regn.attributes["value"][0]["value"] }}'
