- alias: Motion off detected on Aeotec
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    to: '0'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall_nere
    - service: switch.turn_off
      entity_id: switch.shelly_shplg_s_801101

- alias: Motion detected on Aeotec
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    to: '8'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_nere
        brightness: 255
    - service: switch.turn_on
      entity_id: switch.shelly_shplg_s_801101
