- alias: Daily Backup at 3 AM
  trigger:
    platform: time
    at: '3:00:00'
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    - service: persistent_notification.create
      data_template:
        title: Backup created
        message: Creating backup named "Automated Backup {{ now().strftime('%Y-%m-%d') }}"
    - delay: '01:00:00'
    - service: hassio.addon_stdin
      data_template:
        addon: "7be23ff5_dropbox_sync"
        input: {"command":"upload"}
