- alias: Check batteries every evening
  trigger:
    - platform: time
      at: '18:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: python_script.battery_checker
      data:
        threshold: 50
