- alias: Sunrise actions
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:45:00'
  action:
    - service: light.turn_off
      entity_id:
        - group.all_lights
        - light.hue_ute_door
    - service: switch.turn_off
      entity_id:
        - switch.balkong_lampor
        - switch.trappa
        - switch.kitchen_taklampa
        - switch.kitchen_window_lights

