- alias: Sunset actions
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: light.turn_on
      entity_id:
        - light.hue_ute_door
        - light.hue_printer
        - light.hue_hall_uppe
    - service: switch.turn_on
      entity_id:
        - switch.balkong_lampor
        - switch.kitchen_window_lights
    - service: light.turn_on
      data:
        entity_id: light.hue_iris_1
        brightness: 255
        effect: colorloop
